services: # services to run
  colorize-api: # name of the first service
    build: 
      context: . # specify the directory of the Dockerfile
      dockerfile: Dockerfile-api # specify the Dockerfile name
    ports:
      - "5000:5000" # specify port mapping
      
  gradio-app:
    build:
      context: . # specify the directory of the Dockerfile
      dockerfile: Dockerfile-gradio # specify the Dockerfile name
    ports:
      - "7860:7860" # specify port mapping
    depends_on:
      - colorize-api # specify service dependencies

  